name: bao-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.1.4
  - pyyaml=6.0.1
  - matplotlib=3.8.3
  - h5py=3.10.0
  - joblib=1.3.2
  - pip
