paths_file: paths.yaml

bao:
  data_file: null
  use_official_covariance: true
  include_proxy: true

sn:
  file: null
  marginalize_m: true

cmb:
  enabled: false

run:
  model: both
  rd_mode: fixed
  workers: -1
  maxiter: 1000
  output: fit_results.json
  save_intermediate: false

seven_d:
  beta0_bounds: [-0.05, 0.05]
  beta1_bounds: [-0.05, 0.05]
  sigma_eps: 0.05
  sigma_soft_limit: 0.05
  sigma_prior_width: 0.02
