bao:
  base_dir: ".."
  datasets:
    - name: "DESI LRG GCcomb z=0.4-0.6"
      mean: "desi_2024_gaussian_bao_LRG_GCcomb_z0.4-0.6_mean.txt"
      covariance: "desi_2024_gaussian_bao_LRG_GCcomb_z0.4-0.6_cov.txt"
    - name: "DESI LRG GCcomb z=0.6-0.8"
      mean: "desi_2024_gaussian_bao_LRG_GCcomb_z0.6-0.8_mean.txt"
      covariance: "desi_2024_gaussian_bao_LRG_GCcomb_z0.6-0.8_cov.txt"
    - name: "DESI LyÎ± GCcomb"
      mean: "desi_2024_gaussian_bao_Lya_GCcomb_mean.txt"
      covariance: "desi_2024_gaussian_bao_Lya_GCcomb_cov.txt"
  legacy_proxy:
    name: "Legacy QSO proxy"
    z: 1.48
    DM_over_rd: 26.07
    err_DM: 0.67
sn:
  base_dir: ".."
  file: "Pantheon+SH0ES.dat"
cmb:
  use_planck_prior: true
